name: app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-99.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  google_sign_in:
  firebase_auth:
  gsheets:
  flutter_typeahead:
  flutter_barcode_scanner:
  fl_chart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/build.png
    - images/googleLogo.png